[workspace]
members = [
    "node",
    # "pallets/template",
    # "pallets/kitties",
    # "pallets/blogchain",
    "pallets/tictactoe",
    "pallets/dex",
    "runtime",
]
[profile.release]
panic = "unwind"
