[workspace]
members = [
    "node",
    # "pallets/template",
    # "pallets/kitties",
    # "pallets/blogchain",
    #"pallets/tictactoe",
    #"pallets/dex",
    "pallets/acala/dex",
    "pallets/acala/modules/traits",
    "primitives",
    "runtime",
]
[profile.release]
panic = "unwind"
